module.exports = {
  CREDENTIALS: {
    USERNAME: 'denis-ext@allwhere.co',
    PASSWORD: 'Password123',
  },
  DEVICE: {
    STATUS: 'Allocated',
    SERIAL_NUMBER: '123456789',
    TYPE: 'Mobile',
    CONDITION: 'A - Like New',
    MAKE: 'Apple',
    MODEL: 'Iphone 15 Pro',
    COLOR: 'Red',
  },
  FILTERS: [
    'Activation Locked',
    'Allocated',
    'Donated',
    'HOLD',
    'Lost',
    'MDM Locked',
    'Pending Allocation',
    'Pending Certification',
    'Pending Quote Approval',
    'Pending Recycle',
    'Pending Repair',
    'Pending Retrieval',
    'Pending Sale',
    'Pending Wipe',
    'Processing Device',
    'Quote in Progress',
    'Recovery Locked',
    'Recycled',
    'Sold',
  ],
};
